### ISSUE TITLE
As a user, when I visit the app, all movies should be displayed

### ISSUE THREAD

**Issue by camjohnson-code** [camjohnson-code/rancid-tomatillos#1]

**Comment by EGavinG** [comment]
**User Story: Visit the Homepage**

**Steps to Accomplish:**
1. Open the web browser.
2. Enter the URL of the application.
3. Press Enter to navigate to the homepage.

**Execution Outcome:**
Upon successful execution, the user sees the application's homepage, which typically includes featured content, navigation options, and any relevant announcements.

**Acceptance Criteria for Developer:**
The developer can consider the user story accomplished if the homepage loads without errors, all elements are displayed correctly, and navigation links work as intended.
