### ISSUE TITLE
As a user, I can click a movie, and see that movie’s details

### ISSUE THREAD

**Issue by camjohnson-code** [camjohnson-code/rancid-tomatillos#2]

**Comment by camjohnson-code** [comment]
- When a movie’s details are displayed, none of the other movies will be visible; it should just be that movie’s details
- When a movie’s details are displayed, the user should have a way to return to the main view of all movies

**Comment by EGavinG** [comment]
**User Story: View a Movie’s Details**

**Steps to Accomplish:**
1. Navigate to the homepage.
2. Browse or search for a specific movie.
3. Click on the movie's title or poster to view its details.

**Execution Outcome:**
After executing the steps, the user is redirected to a dedicated page displaying comprehensive information about the selected movie. This may include the movie synopsis, cast, release date, ratings, and related recommendations.

**Acceptance Criteria for Developer:**
The developer ensures the movie details page loads correctly, and all relevant information is accurately displayed. Additionally, navigation back to the homepage or other sections should work seamlessly.
