### ISSUE TITLE
Create DTR

### ISSUE THREAD

**Issue by camjohnson-code** [camjohnson-code/rancid-tomatillos#3]

**Comment by EGavinG** [comment]
Utilize Notion DTR Template to fill out current details about:

1.  Project Commitment
2. Availability 
3. Strengths 
4. Learning Goals 
5. Project Convention Norms

[DTR Link](https://www.notion.so/Rancid-Tomatillos-c4f4ab3dd4b64a81ab303a772ded6825?pvs=4)
