### ISSUE TITLE
Find 2-3 design inspiration pieces each

### ISSUE THREAD

**Issue by camjohnson-code** [camjohnson-code/rancid-tomatillos#5]

**Comment by EGavinG** [comment]
Provide 2-3 inspiration pieces from related sites to feature in project. 
Utilize the Design Inspo template in Google Docs to submit inspo links and description. 

[Our Design Inspo Doc](https://docs.google.com/document/d/1eTDLDSxLX8VIB_fygDHr2A8FaQ3VDwBbTE2J3CoTlXQ/edit?usp=sharing)
