### ISSUE TITLE
Create wireframes

### ISSUE THREAD

**Issue by camjohnson-code** [camjohnson-code/rancid-tomatillos#6]

**Comment by EGavinG** [comment]
Create wireframes after mutual agreement to layout and design for Project.
Utilize Figma to build wireframes for design layout. 

[Figma Wireframe Link](https://www.figma.com/file/bYBFLsfJ4wEOVgAMR8jFnN/Rancid-Tomatillos-Wireframes?type=design&node-id=0%3A1&mode=design&t=jzHqbZrD7Rhbxg0F-1)
