### ISSUE TITLE
Create project/component architecture

### ISSUE THREAD

**Issue by camjohnson-code** [camjohnson-code/rancid-tomatillos#7]

**Comment by camjohnson-code** [comment]
- What components do you envision needing?
- Where will data be stored?
- How will information be passed around?

**Comment by EGavinG** [comment]
Build Component Architecture rundown with FigmaJam Board tool. 
Discuss file structure and answer questions above together. 


[Figma JamBoard Link](https://www.figma.com/file/JcSW0zDYUKdyGzqnwXSpP9/Rancid-Tomatillos-Component-Architecture?type=whiteboard&node-id=0%3A1&t=GE27yuv94BFmFnBB-1)
