### ISSUE TITLE
As a user, if there's an error on the server-side, I will see a message indicating something went wrong

### ISSUE THREAD

**Issue by camjohnson-code** [camjohnson-code/rancid-tomatillos#8]

**Comment by EGavinG** [comment]
**User Story: Handle Server-Side Errors**

**Steps to Accomplish:**

1. Perform an action that triggers a server-side operation (e.g., submit a form, request data).
2. If an error occurs on the server-side during the operation, display a user-friendly error message.

**Execution Outcome:**
If there's an error on the server-side, the user sees a clear and informative error message on the screen, indicating that something went wrong. The message should help the user understand the nature of the problem and provide guidance on what to do next (e.g., try again later, contact support).

**Acceptance Criteria for Developer:**
The developer can consider the user story accomplished if, during testing, intentionally triggering server-side errors results in the display of appropriate error messages. The error messages should not expose sensitive information, and they should be designed for easy comprehension by users who may not be technically inclined.

**Additional Considerations:**
Implement logging on the server to capture details of the errors for debugging and analysis purposes.
Ensure that error messages are consistent in style and tone with the rest of the application.
If applicable, include error codes that can be used by support teams for troubleshooting.
Test the user experience by simulating various server-side errors to guarantee that error handling is robust and covers a range of scenarios.
